const express = require("express");
const path = require("path");
const fs = require("fs");
const multer = require("multer");
const ExcelJS = require("exceljs");
const PDFDocument = require("pdfkit");
const db = require("../db");
const service = require("../services/financeiroAvancado");
const router = express.Router();
const uploads = path.join(__dirname,"..","uploads");
const upload = multer({ storage: multer.diskStorage({ destination: uploads, filename: (req,file,cb) => cb(null,`${Date.now()}-${Math.round(Math.random()*1e9)}${path.extname(file.originalname)}`) }) });
const setores = new Set(["Administrativo","Pedagógico","Outro"]), statusFuncionario = new Set(["Ativo","Inativo"]), statusPagamento = new Set(["Pendente","Programado","Pago","Cancelado"]), statusFolha = new Set(["Em preenchimento","Pronta para pagamento","Paga","Cancelada"]);
router.get("/financeiro",async(req,res)=>{const params=[],where=[];for(const [expr,v] of [["f.projeto_id",req.query.projeto_id],["f.curso_id",req.query.curso_id],["f.funcionario_id",req.query.funcionario_id],["fn.setor",req.query.setor],["f.categoria",req.query.categoria],["f.tipo_pagamento",req.query.tipo_pagamento],["f.status",req.query.status]])if(v){params.push(v);where.push(`${expr}=$${params.length}`);}if(req.query.inicio){params.push(req.query.inicio);where.push(`f.data_pagamento >= $${params.length}`);}if(req.query.fim){params.push(req.query.fim);where.push(`f.data_pagamento <= $${params.length}`);}if(req.query.beneficiario){params.push(`%${req.query.beneficiario.trim()}%`);where.push(`COALESCE(fn.nome,f.prestador_nome,'') ILIKE $${params.length}`);}res.json((await db.query(`SELECT f.*,p.nome projeto_nome,c.nome curso_nome,fn.nome funcionario_nome,fn.setor,COALESCE(fn.nome,f.prestador_nome) beneficiario FROM financeiro f LEFT JOIN projetos p ON p.id=f.projeto_id LEFT JOIN cursos c ON c.id=f.curso_id LEFT JOIN funcionarios fn ON fn.id=f.funcionario_id ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY COALESCE(f.data_pagamento,f.criado_em::date) DESC,f.id DESC`,params)).rows);});

const tiposLancamento = new Set(["Prestação de Serviço","Outros"]);
router.post("/lancamentos-financeiros",upload.single("anexo"),async(req,res)=>{
  const d=req.body, valor=Number(d.valor), tipo=String(d.tipo_pagamento||"");
  if(!tiposLancamento.has(tipo)||!d.descricao?.trim()||!d.data_pagamento||!Number.isFinite(valor)||valor<0||!statusPagamento.has(d.status||"Pendente")) return res.status(400).json({erro:"Informe tipo, descrição, valor e data válidos"});
  if(d.projeto_id){const projeto=(await db.query("SELECT id FROM projetos WHERE id=$1",[d.projeto_id])).rows[0];if(!projeto)return res.status(400).json({erro:"Projeto não encontrado"});}
  const categoria=tipo==="Prestação de Serviço"?"Prestação de Serviço":"Outros";
  const row=(await db.query(`INSERT INTO financeiro (projeto_id,categoria,tipo_pagamento,prestador_nome,cpf_cnpj,valor,status,descricao,data_pagamento,observacoes,categoria_detalhe,nf_arquivo,nf_nome_original) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[d.projeto_id||null,categoria,tipo,d.prestador_nome?.trim()||null,d.cpf_cnpj?.trim()||null,valor,d.status||"Pendente",d.descricao.trim(),d.data_pagamento,d.observacoes?.trim()||null,d.categoria_detalhe?.trim()||null,req.file?.filename||null,req.file?.originalname||null])).rows[0];
  await db.query("INSERT INTO historico_alteracoes (entidade,entidade_id,acao,dados,usuario_id) VALUES ('lancamento_financeiro',$1,'criado',$2,$3)",[row.id,JSON.stringify(d),req.usuario.id]);res.status(201).json(row);
});
router.put("/lancamentos-financeiros/:id",async(req,res)=>{
  const d=req.body,valor=Number(d.valor),tipo=String(d.tipo_pagamento||"");
  if(!tiposLancamento.has(tipo)||!d.descricao?.trim()||!d.data_pagamento||!Number.isFinite(valor)||valor<0||!statusPagamento.has(d.status))return res.status(400).json({erro:"Informe tipo, descrição, valor e data válidos"});
  const row=(await db.query(`UPDATE financeiro SET projeto_id=$1,categoria=$2,tipo_pagamento=$3,prestador_nome=$4,cpf_cnpj=$5,valor=$6,status=$7,descricao=$8,data_pagamento=$9,observacoes=$10,categoria_detalhe=$11 WHERE id=$12 AND funcionario_id IS NULL AND folha_auxilio_id IS NULL RETURNING *`,[d.projeto_id||null,tipo==="Prestação de Serviço"?"Prestação de Serviço":"Outros",tipo,d.prestador_nome?.trim()||null,d.cpf_cnpj?.trim()||null,valor,d.status,d.descricao.trim(),d.data_pagamento,d.observacoes?.trim()||null,d.categoria_detalhe?.trim()||null,req.params.id])).rows[0];
  if(!row)return res.status(404).json({erro:"Lançamento não encontrado ou gerenciado por outro fluxo"});
  await db.query("INSERT INTO historico_alteracoes (entidade,entidade_id,acao,dados,usuario_id) VALUES ('lancamento_financeiro',$1,'atualizado',$2,$3)",[row.id,JSON.stringify(d),req.usuario.id]);res.json(row);
});

router.get("/funcionarios", async (req,res) => {
  const params=[]; const where=[];
  for (const [campo,valor] of [["setor",req.query.setor],["status",req.query.status]]) if(valor){params.push(valor);where.push(`${campo}=$${params.length}`);}
  const busca=req.query.busca?.trim(); if(busca){params.push(`%${busca}%`);where.push(`(nome ILIKE $${params.length} OR cpf ILIKE $${params.length})`);}
  res.json((await db.query(`SELECT * FROM funcionarios ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY nome`,params)).rows);
});
router.post("/funcionarios", async (req,res) => {
  const d=req.body; if(!d.nome?.trim()||!d.cpf?.trim()||!setores.has(d.setor)||!statusFuncionario.has(d.status||"Ativo")) return res.status(400).json({erro:"Preencha nome, CPF, setor e status válidos"});
  const row=(await db.query(`INSERT INTO funcionarios (nome,cpf,chave_pix,cargo,setor,tipo_vinculo,telefone,email,status,observacoes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[d.nome.trim(),d.cpf.trim(),d.chave_pix||"",d.cargo||"",d.setor,d.tipo_vinculo||"",d.telefone||null,d.email||null,d.status||"Ativo",d.observacoes||null])).rows[0]; res.status(201).json(row);
});
router.put("/funcionarios/:id", async (req,res) => {
  const d=req.body; if(!d.nome?.trim()||!d.cpf?.trim()||!setores.has(d.setor)||!statusFuncionario.has(d.status)) return res.status(400).json({erro:"Dados inválidos"});
  const row=(await db.query(`UPDATE funcionarios SET nome=$1,cpf=$2,chave_pix=$3,cargo=$4,setor=$5,tipo_vinculo=$6,telefone=$7,email=$8,status=$9,observacoes=$10,atualizado_em=CURRENT_TIMESTAMP WHERE id=$11 RETURNING *`,[d.nome.trim(),d.cpf.trim(),d.chave_pix||"",d.cargo||"",d.setor,d.tipo_vinculo||"",d.telefone||null,d.email||null,d.status,d.observacoes||null,req.params.id])).rows[0]; if(!row)return res.status(404).json({erro:"Funcionário não encontrado"});res.json(row);
});

router.get("/pagamentos-funcionarios", async (req,res) => {
  const params=[], where=[]; for(const [expr,v] of [["p.projeto_id",req.query.projeto_id],["p.funcionario_id",req.query.funcionario_id],["f.setor",req.query.setor],["p.status",req.query.status]])if(v){params.push(v);where.push(`${expr}=$${params.length}`);}
  if(req.query.inicio){params.push(req.query.inicio);where.push(`p.data_pagamento >= $${params.length}`);} if(req.query.fim){params.push(req.query.fim);where.push(`p.data_pagamento <= $${params.length}`);}
  res.json((await db.query(`SELECT p.*,f.nome funcionario_nome,f.chave_pix,f.cargo,f.setor,pr.nome projeto_nome FROM pagamentos_funcionarios p JOIN funcionarios f ON f.id=p.funcionario_id LEFT JOIN projetos pr ON pr.id=p.projeto_id ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY p.criado_em DESC`,params)).rows);
});
router.post("/pagamentos-funcionarios", upload.single("anexo"), async (req,res) => {
  const d=req.body, valor=Number(d.valor), competencia=d.competencia||String(d.data_pagamento||"").slice(0,7); if(!d.funcionario_id||!d.data_pagamento||!competencia||!d.descricao?.trim()||!Number.isFinite(valor)||valor<0||!statusPagamento.has(d.status||"Pendente")) return res.status(400).json({erro:"Informe funcionário, descrição, valor e data válidos"});
  const row=await db.transaction(async(client)=>{const fin=(await client.query(`INSERT INTO financeiro (projeto_id,funcionario_id,categoria,tipo_pagamento,valor,status,descricao,data_pagamento,observacoes) VALUES ($1,$2,'Pagamento de funcionário','Funcionário',$3,$4,$5,$6,$7) RETURNING id`,[d.projeto_id||null,d.funcionario_id,valor,d.status||"Pendente",d.descricao.trim(),d.data_pagamento,d.observacoes||null])).rows[0];const p=(await client.query(`INSERT INTO pagamentos_funcionarios (funcionario_id,projeto_id,competencia,data_pagamento,descricao,valor,status,responsavel,observacoes,financeiro_id,criado_por) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[d.funcionario_id,d.projeto_id||null,competencia,d.data_pagamento,d.descricao.trim(),valor,d.status||"Pendente",d.responsavel||null,d.observacoes||null,fin.id,req.usuario.id])).rows[0];if(req.file)await client.query("INSERT INTO anexos_pagamentos (pagamento_funcionario_id,tipo,arquivo,nome_original) VALUES ($1,$2,$3,$4)",[p.id,d.tipo_anexo||"Comprovante",req.file.filename,req.file.originalname]);await service.historico(client,"pagamento_funcionario",p.id,"criado",d,req.usuario.id);return p;});res.status(201).json(row);
});
router.put("/pagamentos-funcionarios/:id", async(req,res)=>{const d=req.body,valor=Number(d.valor);if(!statusPagamento.has(d.status)||!Number.isFinite(valor)||valor<0)return res.status(400).json({erro:"Pagamento inválido"});const row=await db.transaction(async(client)=>{const p=(await client.query(`UPDATE pagamentos_funcionarios SET projeto_id=$1,competencia=$2,data_pagamento=$3,descricao=$4,valor=$5,status=$6,responsavel=$7,observacoes=$8,atualizado_em=CURRENT_TIMESTAMP WHERE id=$9 RETURNING *`,[d.projeto_id||null,d.competencia,d.data_pagamento||null,d.descricao,valor,d.status,d.responsavel||null,d.observacoes||null,req.params.id])).rows[0];if(!p)return null;await client.query("UPDATE financeiro SET projeto_id=$1,valor=$2,status=$3,descricao=$4,data_pagamento=$5 WHERE id=$6",[p.projeto_id,p.valor,p.status,p.descricao,p.data_pagamento,p.financeiro_id]);await service.historico(client,"pagamento_funcionario",p.id,"atualizado",d,req.usuario.id);return p;});if(!row)return res.status(404).json({erro:"Pagamento não encontrado"});res.json(row);});

router.get("/folhas-auxilio", async(req,res)=>{const params=[],where=[];for(const [c,v] of [["f.projeto_id",req.query.projeto_id],["f.curso_id",req.query.curso_id],["f.status",req.query.status]])if(v){params.push(v);where.push(`${c}=$${params.length}`);}res.json((await db.query(`SELECT f.*,p.nome projeto_nome,c.nome curso_nome,c.municipio,i.nome instrutor_nome,COUNT(a.id)::int total_alunos,COALESCE(SUM(a.valor_total),0) total_folha,COALESCE(SUM(a.valor_total) FILTER(WHERE a.status='Pago'),0) total_pago FROM folhas_auxilio_transporte f JOIN projetos p ON p.id=f.projeto_id JOIN cursos c ON c.id=f.curso_id LEFT JOIN instrutores i ON i.id=c.instrutor_id LEFT JOIN itens_auxilio_transporte a ON a.folha_id=f.id ${where.length?`WHERE ${where.join(" AND ")}`:""} GROUP BY f.id,p.nome,c.nome,c.municipio,i.nome ORDER BY f.criado_em DESC`,params)).rows);});
router.post("/folhas-auxilio", async(req,res)=>{const d=req.body,v=Number(d.valor_diario??9);if(!d.projeto_id||!d.curso_id||!d.periodo_inicial||!d.periodo_final||!d.responsavel?.trim()||v<0)return res.status(400).json({erro:"Dados da folha inválidos"});try{const folha=await db.transaction(async(client)=>{const curso=(await client.query("SELECT id FROM cursos WHERE id=$1 AND projeto_id=$2",[d.curso_id,d.projeto_id])).rows[0];if(!curso)throw new Error("Curso não pertence ao projeto");const f=(await client.query(`INSERT INTO folhas_auxilio_transporte (projeto_id,curso_id,periodo_inicial,periodo_final,valor_diario,responsavel,criado_por) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[d.projeto_id,d.curso_id,d.periodo_inicial,d.periodo_final,v,d.responsavel.trim(),req.usuario.id])).rows[0];await client.query(`INSERT INTO itens_auxilio_transporte (folha_id,aluno_id,valor_diario,status) SELECT $1,id,$2,CASE WHEN COALESCE(nome,'')='' OR COALESCE(chave_pix,'')='' THEN 'Dados incompletos' ELSE 'Aguardando validação' END FROM alunos WHERE curso_id=$3 AND tipo='aluno'`,[f.id,v,d.curso_id]);await service.historico(client,"folha_auxilio",f.id,"criada",d,req.usuario.id);return f;});res.status(201).json(folha);}catch(e){if(e.code==='23505')return res.status(409).json({erro:"Já existe uma folha para este curso e período"});throw e;}});
router.get("/folhas-auxilio/:id", async(req,res)=>{const folha=(await db.query(`SELECT f.*,p.nome projeto_nome,c.nome curso_nome,c.municipio,i.nome instrutor_nome FROM folhas_auxilio_transporte f JOIN projetos p ON p.id=f.projeto_id JOIN cursos c ON c.id=f.curso_id LEFT JOIN instrutores i ON i.id=c.instrutor_id WHERE f.id=$1`,[req.params.id])).rows[0];if(!folha)return res.status(404).json({erro:"Folha não encontrada"});const itens=(await db.query(`SELECT it.*,a.nome,a.cpf,a.chave_pix FROM itens_auxilio_transporte it JOIN alunos a ON a.id=it.aluno_id WHERE it.folha_id=$1 ORDER BY a.nome`,[req.params.id])).rows.map(i=>({...i,faltantes:service.validarPronto(i,i.quantidade_presencas,i.valor_total)}));res.json({...folha,itens});});
router.put("/folhas-auxilio/:folhaId/itens/:itemId",async(req,res)=>{const item=await service.atualizarItem(req.params.folhaId,req.params.itemId,req.body,req.usuario.id);if(!item)return res.status(404).json({erro:"Item não encontrado"});res.json(item);});
router.post("/folhas-auxilio/:id/pagamentos-lote",upload.single("comprovante"),async(req,res)=>{const ids=JSON.parse(req.body.item_ids||"[]");if(!Array.isArray(ids)||!ids.length||!req.body.data_pagamento||!req.body.responsavel?.trim())return res.status(400).json({erro:"Selecione alunos, data e responsável"});await db.transaction(async(client)=>{for(const id of ids){const item=(await client.query(`SELECT it.*,a.nome,a.chave_pix FROM itens_auxilio_transporte it JOIN alunos a ON a.id=it.aluno_id WHERE it.id=$1 AND it.folha_id=$2 FOR UPDATE`,[id,req.params.id])).rows[0];if(!item)continue;const faltam=service.validarPronto(item,item.quantidade_presencas,item.valor_total);if(faltam.length)throw new Error(`${item.nome}: faltam ${faltam.join(", ")}`);await client.query("UPDATE itens_auxilio_transporte SET status='Pago',data_pagamento=$1,responsavel_pagamento=$2,observacoes=COALESCE($3,observacoes),atualizado_em=CURRENT_TIMESTAMP WHERE id=$4",[req.body.data_pagamento,req.body.responsavel,req.body.observacoes||null,id]);if(req.file)await client.query("INSERT INTO anexos_pagamentos (item_auxilio_id,tipo,arquivo,nome_original) VALUES ($1,'Comprovante',$2,$3)",[id,req.file.filename,req.file.originalname]);}await service.historico(client,"folha_auxilio",req.params.id,"pagamento_lote",{item_ids:ids},req.usuario.id);});res.json({ok:true});});
router.put("/folhas-auxilio/:id/status",async(req,res)=>{if(!statusFolha.has(req.body.status))return res.status(400).json({erro:"Status inválido"});const row=await db.transaction(async(client)=>{if(req.body.status==="Paga"){const pendentes=Number((await client.query("SELECT COUNT(*) total FROM itens_auxilio_transporte WHERE folha_id=$1 AND status NOT IN ('Pago','Pagamento não realizado')",[req.params.id])).rows[0].total);if(pendentes)throw new Error("Finalize todos os pagamentos antes de marcar a folha como paga");}const f=(await client.query("UPDATE folhas_auxilio_transporte SET status=$1,responsavel=COALESCE($2,responsavel),atualizado_em=CURRENT_TIMESTAMP WHERE id=$3 RETURNING *",[req.body.status,req.body.responsavel||null,req.params.id])).rows[0];if(!f)return null;await service.sincronizarFinanceiro(client,f.id);await service.historico(client,"folha_auxilio",f.id,"status",req.body,req.usuario.id);return f;});if(!row)return res.status(404).json({erro:"Folha não encontrada"});res.json(row);});
router.get("/historico/:entidade/:id",async(req,res)=>res.json((await db.query("SELECT h.*,u.nome usuario_nome FROM historico_alteracoes h LEFT JOIN usuarios u ON u.id=h.usuario_id WHERE entidade=$1 AND entidade_id=$2 ORDER BY h.criado_em DESC",[req.params.entidade,req.params.id])).rows));

async function dadosExportacao(id){return (await db.query(`SELECT f.*,p.nome projeto_nome,c.nome curso_nome,c.municipio,i.nome instrutor_nome,json_agg(json_build_object('nome',a.nome,'pix',a.chave_pix,'presencas',it.quantidade_presencas,'valor_diario',it.valor_diario,'total',it.valor_total) ORDER BY a.nome) itens FROM folhas_auxilio_transporte f JOIN projetos p ON p.id=f.projeto_id JOIN cursos c ON c.id=f.curso_id LEFT JOIN instrutores i ON i.id=c.instrutor_id JOIN itens_auxilio_transporte it ON it.folha_id=f.id JOIN alunos a ON a.id=it.aluno_id WHERE f.id=$1 GROUP BY f.id,p.nome,c.nome,c.municipio,i.nome`,[id])).rows[0];}
router.get("/folhas-auxilio/:id/excel",async(req,res)=>{const f=await dadosExportacao(req.params.id);if(!f)return res.status(404).json({erro:"Folha não encontrada"});const w=new ExcelJS.Workbook(),s=w.addWorksheet("Auxílio-transporte");s.addRows([["Projeto",f.projeto_nome],["Curso",f.curso_nome],["Município",f.municipio||""],["Instrutor",f.instrutor_nome||""],["Período",`${f.periodo_inicial} a ${f.periodo_final}`],["Responsável",f.responsavel],["Gerado em",new Date().toLocaleString("pt-BR")],[],["Nº","Aluno","Pix","Presenças","Valor diário","Total"]]);f.itens.forEach((i,n)=>s.addRow([n+1,i.nome,i.pix,i.presencas,Number(i.valor_diario),Number(i.total)]));s.addRow(["","TOTAL","","","",f.itens.reduce((a,i)=>a+Number(i.total),0)]);res.setHeader("Content-Type","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");res.setHeader("Content-Disposition",`attachment; filename=auxilio-${f.id}.xlsx`);await w.xlsx.write(res);res.end();});
router.get("/folhas-auxilio/:id/pdf",async(req,res)=>{const f=await dadosExportacao(req.params.id);if(!f)return res.status(404).json({erro:"Folha não encontrada"});res.setHeader("Content-Type","application/pdf");res.setHeader("Content-Disposition",`attachment; filename=auxilio-${f.id}.pdf`);const d=new PDFDocument({margin:35});d.pipe(res);d.fontSize(16).text("Folha de auxílio-transporte",{align:"center"});d.moveDown().fontSize(10).text(`Projeto: ${f.projeto_nome}\nCurso: ${f.curso_nome} | Município: ${f.municipio||"-"}\nInstrutor: ${f.instrutor_nome||"-"}\nPeríodo: ${f.periodo_inicial} a ${f.periodo_final}\nResponsável: ${f.responsavel}`);d.moveDown();f.itens.forEach((i,n)=>d.text(`${n+1}. ${i.nome} | Pix: ${i.pix||"-"} | ${i.presencas} presença(s) | R$ ${Number(i.total).toFixed(2)}`));d.moveDown().font("Helvetica-Bold").text(`Total geral: R$ ${f.itens.reduce((a,i)=>a+Number(i.total),0).toFixed(2)}`);d.end();});
module.exports=router;
